name: lagon

on:
  push:
    branches:
      - main
      - lagon

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: corepack enable
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm
      - run: pnpm install
      - run: pnpm build
        env:
          NITRO_PRESET: lagon
      - name: Update lagon config
        run: echo '{"function_id":"cleoau1wk0000mj0843yvsgi7","organization_id":"cleeepy2j0006jx08ew36ivpg","index":"server/index.mjs","client":null,"assets":"public"}' > .output/.lagon/config.json
      - name: Update logon token
        run: mkdir -p ~/.lagon && echo \{\"token\":\"${LAGON_TOKEN}\",\"site_url\":\"https://dash.lagon.app\"\} > ~/.lagon/config.json
        env:
          LAGON_TOKEN: ${{ secrets.LAGON_TOKEN }}
      - name: Lagon deploy
        run: npx lagon deploy --prod .output
